---
- name: Deploy Docker Images to Kubernetes
  hosts: localhost
  vars_files:
    - vault.yml
  vars:
    dockerhub_username: "krutikpatel"
    configmap_file: "configmap.yml"
    k8s_deployment_file: "k8s-deployment.yml"
  roles:
    - role: common
  tasks:
    - name: Apply Kubernetes ConfigMap
      kubernetes.core.k8s:
        definition: "{{ lookup('file', configmap_file) }}"

    - name: Apply Kubernetes Deployment
      kubernetes.core.k8s:
        definition: "{{ lookup('file', k8s_deployment_file) }}"
