---
# tasks file for common
- name: Install NTP package
  apt:
    name: ntp
    state: present
  become: yes

- name: Ensure NTP service is running and enabled
  service:
    name: ntp
    state: started
    enabled: yes
  become: yes

- name: Configure NTP servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart NTP service
  become: yes